// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PupilAdmissions.Infrastructure;

#nullable disable

namespace PupilAdmissions.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908230603_ChangeLengthOfStayToTermsEnum")]
    partial class ChangeLengthOfStayToTermsEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("PupilAdmissions.Domain.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "System"
                        });
                });

            modelBuilder.Entity("PupilAdmissions.Domain.ChangeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("PupilId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("PupilId");

                    b.ToTable("ChangeHistories", (string)null);
                });

            modelBuilder.Entity("PupilAdmissions.Domain.InternationalDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DepositDetail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PupilId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PupilId")
                        .IsUnique();

                    b.ToTable("InternationalDetails", (string)null);
                });

            modelBuilder.Entity("PupilAdmissions.Domain.Pupil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoardingType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsShortStay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YearGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pupils", (string)null);
                });

            modelBuilder.Entity("PupilAdmissions.Domain.ShortStayDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InternationalDetailId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LengthOfStay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PupilId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InternationalDetailId");

                    b.HasIndex("PupilId")
                        .IsUnique();

                    b.ToTable("ShortStayDetails", (string)null);
                });

            modelBuilder.Entity("PupilAdmissions.Domain.ChangeHistory", b =>
                {
                    b.HasOne("PupilAdmissions.Domain.ApplicationUser", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PupilAdmissions.Domain.Pupil", "Pupil")
                        .WithMany("ChangeHistories")
                        .HasForeignKey("PupilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Pupil");
                });

            modelBuilder.Entity("PupilAdmissions.Domain.InternationalDetail", b =>
                {
                    b.HasOne("PupilAdmissions.Domain.Pupil", "Pupil")
                        .WithOne("InternationalDetail")
                        .HasForeignKey("PupilAdmissions.Domain.InternationalDetail", "PupilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pupil");
                });

            modelBuilder.Entity("PupilAdmissions.Domain.ShortStayDetail", b =>
                {
                    b.HasOne("PupilAdmissions.Domain.InternationalDetail", "InternationalDetail")
                        .WithMany()
                        .HasForeignKey("InternationalDetailId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PupilAdmissions.Domain.Pupil", "Pupil")
                        .WithOne("ShortStayDetail")
                        .HasForeignKey("PupilAdmissions.Domain.ShortStayDetail", "PupilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InternationalDetail");

                    b.Navigation("Pupil");
                });

            modelBuilder.Entity("PupilAdmissions.Domain.Pupil", b =>
                {
                    b.Navigation("ChangeHistories");

                    b.Navigation("InternationalDetail");

                    b.Navigation("ShortStayDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
